[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = bblanchon/ArduinoJson@6.21.5
build_flags =
  -D IOT_RED_PIN=25
  -D IOT_GREEN_PIN=26
  -D IOT_BLUE_PIN=27
  -D IOT_COMMON_ANODE=0
  -Wall
  -Wextra
